[build]
functions = "netlify/functions"
command = "echo 'Static files are ready for deployment. No build process required.'"
publish = "."

[[redirects]]
from = "/api/content.json"
to = "/.netlify/functions/content"
status = 200

[[redirects]]
from = "/api/content/:slug"
to = "/.netlify/functions/content-by-slug"
status = 200

[functions]
node_bundler = "esbuild"